title: Dynamic Reflections Psychology
email: drjuliegriffin@dynamicreflectionspsychology.com
phone_number: 720-551-5570
address: "7310 W 52nd Ave #A269 Arvada CO 80002"
description: > #
  Dr. Julie Melowsky Griffin, PsyD obtained her doctoral degree in Psychology from the University of Denver in 2017. 
  She specializes in individual therapy with teens and adults, couples and family therapy. Julie provides animal assisted therapy with her 
  certfiied therapy dog, Lexie Waffles.

google_analytics_id: UA-105831604-1
google_site_verification: SQXqp7bP6yWrnkXTdfDyKPehNJ9EyaSaNg5Stmh5gsg
google_maps_api_key: AIzaSyC4DHSne1itZ1-MkC6PMDZwWvxeHgFttQc

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.md
  - .sass-cache
  - .jekyll-cache